node {
    docker.image('maven:3.9.0').inside('-v /root/.m2:/root/.m2') {  
        stage('Build') {
            sh 'mvn -B -e -DskipTests clean package'
        }

        stage('Test') {
            sh 'mvn test'
            junit 'target/surefire-reports/*.xml'
        }

        stage('Manual Approval') {
            input message: 'Lanjutkan ke tahap Deploy?'
        }

        stage('Deploy') {
            sh './jenkins/scripts/deliver.sh'
            
            def target_host = "jenkins-blueocean"
            def target_user = "root"
            def target_dir = "/home/app"
            def jar_file = "/var/jenkins_home/workspace/submission-cicd-pipeline-reky_arch/?/.m2/repository/com/mycompany/app/my-app/1.0-SNAPSHOT/my-app-1.0-SNAPSHOT.jar"
            def ssh_key = "/var/jenkins_home/.ssh/id_rsa"

//            sh "ssh -i ${ssh_key} ${target_user}@${target_host} 'mkdir -p ${target_dir}'"
            sh "echo 'Sedang upload file...'"
            sh "scp -i ${ssh_key} ${jar_file} ${target_user}@${target_host}:${target_dir}"
            sh "echo 'File sudah diupload'"
            
            sleep(60) //jeda 1 menit

        }
    }
}